### ISSUE TITLE
segmentation not loading

### ISSUE THREAD

**Issue by GaiaBes** [Abe404/root_painter#14] opened 2021-09-22 19:01 UTC
Hi there! I have a problem with loading the segmentation. I do all the steps in the setup and then i open the rootpainter application and start a new project with the biopores dataset and the first image appears. But the "loading segmentation" never goes away, no matter how much i wait. I also check the server output but it doesen't say anything, it stays on "checking for instructions". 
I don't understand why it does that.
Thank you for the attention
:)

**Comment by Abe404** [comment] 2021-09-22 19:06
Hi!

Sounds like a problem with file sync between the client and server.

I suspect that the instruction is not making it to the server, which happens via the file sync software you are using.

How are you running the RootPainter server? Are you using google colab?

**Comment by GaiaBes** [comment] 2021-09-22 19:09
Hi! Yes I am using google colab

**Comment by Abe404** [comment] 2021-09-22 21:48
Is this the first time you are setting it up? Or have you been using it a while and it has suddenly stopped working?

**Comment by GaiaBes** [comment] 2021-09-23 08:14
actually i tried setting it up two months ago, but i never finished doing it, but the segmentation loading worked at the time. And now I am trying again but i have this problem. 
My aim is then to use Rootpainter for my own dataset of photos. 
Yesterday I even tried to use my own dataset but it doesn't load the segmentation even for them.

**Comment by Abe404** [comment] 2021-09-23 08:18
I think the issue is with the sync software. Have you installed google 'Backup and Sync' as described in the tutorial?
Have you checked that the drive_rp_sync folder is available locally on your machine in your google drive folder?
There is also a small status icon for the google backup and sync software. Can you click this and check if it is still syncing files or if it failed in some way?

Thanks for your patience. I am sure we will figure this out.

**Comment by Abe404** [comment] 2021-09-23 08:35
It also looks like google plans to decommission 'Backup and Sync' in favour of  'Drive for desktop' [0]

So the issue might be related to the Backup and Sync software being cancelled soon. This could be a good time for us to test out a new sync solution. Anything that syncs local files with google drive would work.

I will start testing 'Drive for desktop' and let you know how it goes. There seems to be an update option available when clicking the 'backup and sync' status icon. I think it makes more sense to figure out a solution with 'Drive for desktop' as 'Backup and Sync' won't be supported by google for much longer.

[0] https://workspaceupdates.googleblog.com/2021/07/google-drive-backup-and-sync-transition.html

**Comment by Abe404** [comment] 2021-09-23 08:59
I tried with Drive for Desktop and it seems to work ok. I suggest you try this.

I used the streaming rather than mirror option (to make setup quicker, as I have 8GB+ in google drive now).

Streaming can result in slow image loading on the client for larger images. To mitigate this you can right click the folder in google drive (in your local file system) and set 'Offline access' as 'Available Offline', which provides a substantial speedup.

let me know how it goes.

**Comment by GaiaBes** [comment] 2021-09-23 17:01
Hi! thanks for the replies
I think i figured out what the problem is but i cannot solve it.
Two moths ago, when I downloaded Rootpainter for the first time and I used it, I specified as sync directory a Google drive folder on my disc.
Now with the Drive for desktop all the file that i decide to sync go in a different part of the computer: like a new disc called G:Google Drive. 
The problem is that when i open Rootpainter it doesnt ask me to specify a new sync directory, as this is a thing that is asked only the first time, and I had already selected it two months ago when i opened Rootpainter for the first time. --> So my conclusion is that the dataset with the biopores that the client uses is not the one synced in G:Google Drive and so it is not connected with the server --> and for this reason it doesn't load the segmentation

**Comment by GaiaBes** [comment] 2021-09-23 17:20
I deleted everything from the G:Google drive and also from the old folder and i also disinstalled Rootpainter.
I now tried to install Rootpainter again and follow the setup instruction as if it is the first time only. When i mount the drive and stuff it all goes on G:Google Drive. And it is okay.
I run the server and everything is good and all the folders are synced.
BUT when i install Rootpainter and i open it IT DOESN'T ASK ME TO "Specify RootPainter sync_directory locally (First time only)
When opening the client for the first time you will be prompted to specify the sync_directory." and it goes directly to the menu with "create a new project" . 
And if I simulate to create a new project and I specify as image directory the Biopores_750_training folder in the dataset folder that is synced in G:Google drive it says this: "Project creation error: when creating a project the selected dataset must be in the datasets folder. The selected dataset is G:Google Drive\drive_rp_sync\datasets\biopores_750_training and the datasets folder is C:\users\gaiab\Google Drive\drive_rp_sync\datasets."
So they don't match but i also tried to move the biopores folder in the nominated Google Drive folder but in this way it is not synced: If i do this way I can create a new project and the first image appears but it doesn't load the segmentation.

**Comment by GaiaBes** [comment] 2021-09-23 17:24
I thought that the only way to solve this was to uninstall Rootpainter and reinstall it again in order to be able to specify as sync directory the new one in G:Google Drive but Rootpainter didin't ask me to do that after i reinstalled it. It is like he memorised the old Google Drive folder and it cannot be changed. 
Sorry for the long explanation but i am becoming crazy on trying to understand what is wrong.
Hope it helps
Gaia

**Comment by Abe404** [comment] 2021-09-23 18:02
Hey Gaia,

Sorry about the frustration. The sync directory is specified in the root_painter_settings.json file which is located in your  home folder (the folder for your user on your operating system).

If you delete the root_painter_settings.json file then when you open RootPainter again it will ask you to respecify a new sync directory.

The root_painter_settings.json file doesn't get deleted when you uninstall RootPainter

I hope that helps.

From my perspective, I think I should make it easier for users to re-specify the sync directory from the interface. Perhaps an option from a settings menu or something like that. Do you think that might help other users avoid this confusion?

Kind regards,
Abraham

**Comment by Abe404** [comment] 2021-09-23 18:32
The relevant part from the paper:

"Users will be prompted to input the sync directory relative to their own file system when they open the client application for the first time and it will be automatically stored in their home folder in a file named root_painter_settings.json which the user may delete or modify if required."

**Comment by GaiaBes** [comment] 2021-09-23 21:09
yes it helped! it's working!
and yes i think it would help to have a respecify option. 
thank you a lot for your help. really a lot.
I have one last question. Since i have my own dataset of 288 images of roots to analise, do I need to train the model for the biopores first anyway or can i start immediately with my own?
And I just need to put the roots folder in the synced dataset folder and i can use it, right?

**Comment by Abe404** [comment] 2021-09-23 21:12
Great!

I suggest doing a bit more of the tutorial and training a biopore model just to get some practice and to check everything is working ok for you.

You could just use your own images but if your images are really big you might want to split them up first. There's a section on this in the paper called 'create training dataset'. RootPainter has functionality to handle this for you.

**Closed** 2021-09-24 14:26 UTC
